/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'victor' at '14/01/16 19:54' with Gradle 2.9
 *
 * @author victor, @date 14/01/16 19:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
